server:
  port: 10010
spring:
  application:
    name: gateway
eureka:
  client:
    registry-fetch-interval-seconds: 5 # 获取服务列表的周期：5s
    service-url:
      defaultZone: http://127.0.0.1:8888/eureka
  instance:
     prefer-ip-address: true
     lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
     lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
zuul:
  add-host-header: false #允许携带域名信息
  prefix: /api
  routes:
    boke-client: /student/**
    visit-static:
      path: /static/**
      url: http://localhost:8081/static/
    
jwt:
  config:
    key: bwie
   

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000 # 熔断超时时长 5s

ribbon:
  ConnectionTimeout: 10000
  ReadTimeout: 10000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 0

